# Generated by Django 5.0.6 on 2024-06-02 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_precio_diario_inventario_precio_unitario_diario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_articulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('en_stock', models.IntegerField(default=0)),
                ('codigo_barras', models.CharField(blank=True, default='', max_length=100)),
                ('fabricante', models.CharField(blank=True, default='', max_length=100)),
                ('unidad_medida', models.CharField(blank=True, default='', max_length=50)),
                ('precio_unitario_diario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ultimo_precio_compra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grupo_articulos', models.CharField(default='ALIMENTOS', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Consumibles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_articulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('en_stock', models.IntegerField(default=0)),
                ('codigo_barras', models.CharField(blank=True, default='', max_length=100)),
                ('fabricante', models.CharField(blank=True, default='', max_length=100)),
                ('unidad_medida', models.CharField(blank=True, default='', max_length=50)),
                ('precio_unitario_diario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ultimo_precio_compra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grupo_articulos', models.CharField(default='CONSUMIBLES', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EPPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_articulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('en_stock', models.IntegerField(default=0)),
                ('codigo_barras', models.CharField(blank=True, default='', max_length=100)),
                ('fabricante', models.CharField(blank=True, default='', max_length=100)),
                ('unidad_medida', models.CharField(blank=True, default='', max_length=50)),
                ('precio_unitario_diario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ultimo_precio_compra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grupo_articulos', models.CharField(default='EPPS', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_articulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('en_stock', models.IntegerField(default=0)),
                ('codigo_barras', models.CharField(blank=True, default='', max_length=100)),
                ('fabricante', models.CharField(blank=True, default='', max_length=100)),
                ('unidad_medida', models.CharField(blank=True, default='', max_length=50)),
                ('precio_unitario_diario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ultimo_precio_compra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grupo_articulos', models.CharField(default='EQUIPOS', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Herramientas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_articulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('en_stock', models.IntegerField(default=0)),
                ('codigo_barras', models.CharField(blank=True, default='', max_length=100)),
                ('fabricante', models.CharField(blank=True, default='', max_length=100)),
                ('unidad_medida', models.CharField(blank=True, default='', max_length=50)),
                ('precio_unitario_diario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ultimo_precio_compra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grupo_articulos', models.CharField(default='HERRAMIENTAS', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ManoDeObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_articulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('en_stock', models.IntegerField(default=0)),
                ('codigo_barras', models.CharField(blank=True, default='', max_length=100)),
                ('fabricante', models.CharField(blank=True, default='', max_length=100)),
                ('unidad_medida', models.CharField(blank=True, default='', max_length=50)),
                ('precio_unitario_diario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ultimo_precio_compra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grupo_articulos', models.CharField(default='MANODEOBRA', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Materiales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_articulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('en_stock', models.IntegerField(default=0)),
                ('codigo_barras', models.CharField(blank=True, default='', max_length=100)),
                ('fabricante', models.CharField(blank=True, default='', max_length=100)),
                ('unidad_medida', models.CharField(blank=True, default='', max_length=50)),
                ('precio_unitario_diario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ultimo_precio_compra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grupo_articulos', models.CharField(default='MATERIALES', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Misc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_articulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('en_stock', models.IntegerField(default=0)),
                ('codigo_barras', models.CharField(blank=True, default='', max_length=100)),
                ('fabricante', models.CharField(blank=True, default='', max_length=100)),
                ('unidad_medida', models.CharField(blank=True, default='', max_length=50)),
                ('precio_unitario_diario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ultimo_precio_compra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grupo_articulos', models.CharField(default='MISC', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_articulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('en_stock', models.IntegerField(default=0)),
                ('codigo_barras', models.CharField(blank=True, default='', max_length=100)),
                ('fabricante', models.CharField(blank=True, default='', max_length=100)),
                ('unidad_medida', models.CharField(blank=True, default='', max_length=50)),
                ('precio_unitario_diario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ultimo_precio_compra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grupo_articulos', models.CharField(default='TRANSPORTE', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Inventario',
        ),
    ]
