# Generated by Django 5.0.6 on 2024-05-29 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_articulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('en_stock', models.IntegerField(default=0)),
                ('codigo_barras', models.CharField(blank=True, default='', max_length=100)),
                ('grupo_articulos', models.CharField(blank=True, default='', max_length=100)),
                ('fabricante', models.CharField(blank=True, default='', max_length=100)),
                ('unidad_medida', models.CharField(blank=True, default='', max_length=50)),
                ('ultima_revalorizacion', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ultimo_precio_compra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
