# Generated by Django 5.0.6 on 2024-05-30 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventario',
            old_name='ultima_revalorizacion',
            new_name='precio_diario',
        ),
        migrations.AlterField(
            model_name='inventario',
            name='grupo_articulos',
            field=models.CharField(choices=[('EQUIPOS', 'Equipos'), ('EPPS', 'EPPs'), ('TRANSPORTE', 'Transporte'), ('MATERIALES', 'Materiales'), ('CONSUMIBLES', 'Consumibles'), ('ALIMENTOS', 'Alimentos'), ('MANODEOBRA', 'Mano de Obra'), ('HERRAMIENTAS', 'Herramientas'), ('MISC', 'Miscellaneous')], default='MISC', max_length=100),
        ),
    ]
